exports.environment = process.env.ENVIRONMENT || ""
exports.apiURL = process.env.API_URL || ""
exports.apiToken = process.env.API_TOKEN || ""
exports.username = process.env.API_USERNAME || ""
exports.userPass = process.env.API_USERPASS || ""
